name: Build Image
on:
  push:
    branches: ["main"]
  release:
    types: ["published"]
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
permissions:
  pull-requests: write
  issues: write
  repository-projects: write
  contents: write
  packages: write
jobs:
  buildx:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64,linux/arm64
      - name: Extra metadata for tags
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/r35krag0th/jupyterhub-singleuser:latest
          labels: |
            ${{ steps.meta.outputs.labels }}
            git.commit.sha=${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.revision'] }}
            git.repository_url=${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.source'] }}
